### ISSUE TITLE
enlace empresas publicas

### ISSUE THREAD

**Issue by Angiegiovi** [Angiegiovi/subcep#7]
el boton para adicionar un archivo a un enlace no es muy entendible, si se pinta un texto y agregamos un archivo, este se guarda pero no crea el enlace del documto.

![imagen](https://user-images.githubusercontent.com/25138642/97130822-daa78e00-1718-11eb-902b-2f243503e1a7.png)

**Comment by caleeli** [comment]
Se mejoro el boton, y ahora inserta el enlace al archivo subido directamente al documento.

![image](https://user-images.githubusercontent.com/8028650/98197651-9462e380-1efd-11eb-9b5a-5021aaf95aa4.png)
